demweb/models.py
# pylint: disable=no-member
from flask import current_app

from sqlalchemy.types import JSON

from demweb.extensions import db


class Session(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    time = db.Column(db.DateTime, index=True)
    length = db.Column(db.Float, index=True)
    demoname = db.Column(db.String(255), unique=True)
    mapname = db.Column(db.String(255))
    mapmd5 = db.Column(db.String(32))
    servername = db.Column(db.String(255))
    frames = db.Column(db.Integer)
    ticks = db.Column(db.Integer)
    tickinterval = db.Column(db.Float)
    dirty = db.Column(db.Boolean)

    playtime = db.Column(db.Float, index=True)
    rounds = db.Column(db.Integer, index=True)
    ct_wins = db.Column(db.Integer, index=True)
    t_wins = db.Column(db.Integer, index=True)
    chats = db.Column(db.Integer, index=True)
    deaths = db.Column(db.Integer, index=True)
    kills = db.Column(db.Integer, index=True)
    voice_active = db.Column(db.Float, index=True)
    voice_total = db.Column(db.Float, index=True)
    silence_chunks = db.Column(db.JSON(65535))


class Player(db.Model):
    guid = db.Column(db.String(32), primary_key=True)
    name = db.Column(db.String(32), primary_key=True)
    first_seen = db.Column(db.DateTime, index=True)
    last_seen = db.Column(db.DateTime, index=True)
    playtime = db.Column(db.Float, index=True)
    chats = db.Column(db.Integer, index=True)
    deaths = db.Column(db.Integer, index=True)
    kills = db.Column(db.Integer, index=True)
    voicetime = db.Column(db.Float, index=True)


class PlayerNames(db.Model):
    guid = db.Column(db.String(32), db.ForeignKey('player.guid'), primary_key=True)
    name = db.Column(db.String(32), primary_key=True)
    time = db.Column(db.Float)

    player = db.relationship('Player', backref='names', foreign_keys=[guid])


class PlayerSprays(db.Model):
    guid = db.Column(db.String(32), db.ForeignKey('player.guid'), primary_key=True)
    spray = db.Column(db.String(32), primary_key=True)

    player = db.relationship('Player', backref='sprays', foreign_keys=[guid])


class PlayerSession(db.Model):
    player_guid = db.Column(db.String(32), db.ForeignKey('player.guid'), primary_key=True)
    session_id = db.Column(db.Integer, db.ForeignKey('session.id'), primary_key=True)
    playtime = db.Column(db.Float)
    chats = db.Column(db.Integer)
    deaths = db.Column(db.Integer)
    kills = db.Column(db.Integer)
    voicetime = db.Column(db.Float)

    session = db.relationship('Session', foreign_keys=[session_id])
    player = db.relationship('Player', backref='sessions', foreign_keys=[player_guid])


class Chat(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player_guid = db.Column(db.String(32), db.ForeignKey('player.guid'))
    session_id = db.Column(db.Integer, db.ForeignKey('session.id'))
    tick = db.Column(db.Integer)
    time = db.Column(db.DateTime, index=True)
    name = db.Column(db.String(255))
    chat = db.Column(db.String(1024))


class Event(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    player_guid = db.Column(db.String(32), db.ForeignKey('player.guid'))
    session_id = db.Column(db.Integer, db.ForeignKey('session.id'))
    tick = db.Column(db.Integer)
    time = db.Column(db.DateTime, index=True)
    event = db.Column(db.String(32), index=True)
    data = db.Column(db.JSON(1024))

demweb/app.py
from contextlib import nullcontext
from datetime import datetime, timedelta

from flask import Flask, g, has_app_context, request
from .extensions import default_config


def register_extensions(app):
    from .extensions import db
    db.init_app(app)


def register_jinja2_filters(app):
    import orjson
    with app.app_context():
        @app.template_filter('to_json')
        def to_json(value):
            return orjson.dumps(value).decode('utf-8')

        @app.template_filter('to_duration')
        def to_duration(seconds):
            out = ''
            (days, remainder) = divmod(seconds, 86400)
            (hours, remainder) = divmod(remainder, 3600)
            (minutes, seconds) = divmod(remainder, 60)
            if days:
                out += f'{days:.0f}d '
            if hours:
                out += f'{hours:.0f}h '
            if minutes:
                out += f'{minutes:.0f}m '
            out += f'{seconds:.0f}s'
            return out


def register_blueprints(app):
    with app.app_context():
        # Register blueprints
        from .views import bp as views_bp
        app.register_blueprint(views_bp, url_prefix='/')


def setup_logging(app):
    # Logging
    if app.debug:
        @app.before_request
        def log_before_request():
            g.log_datetime = datetime.now()

        @app.after_request
        def log_after_request(response):
            now = datetime.now()
            delta = (now - g.log_datetime).total_seconds() * 1_000
            dt = now.isoformat().replace('T', ' ').split('.')[0]
            print(f'[{dt}] {request.method} {request.path} -> {response.status} ({delta:.2f}ms)')
            return response


def register_shell_context(app):
    import inspect
    from pprint import pprint

    from flask_sqlalchemy import get_debug_queries

    from demweb import models
    from demweb.extensions import db

    @app.shell_context_processor
    def make_shell_context():
        return {
            'app': app,
            'db': db,
            'query': get_debug_queries,
            'print': pprint,
            **dict(inspect.getmembers(models, inspect.isclass))
        }


def fix_sqlalchemy_uwsgi_multiprocess_bug(app):
    from demweb.extensions import db

    def _dispose_db_pool():
        print('uWSGI+SQLAlchemy: Disposing forked() db pool!')
        with app.app_context() if not has_app_context() else nullcontext():
            db.engine.dispose()

    try:
        from uwsgidecorators import postfork
        postfork(_dispose_db_pool)
    except ImportError:
        pass


def create_app(test_config=None):
    # Create flask application object
    app = Flask(__name__)

    if test_config is None:
        app.config.update(default_config)
    else:
        app.config.update(test_config)

    register_extensions(app)
    register_jinja2_filters(app)
    register_blueprints(app)
    register_shell_context(app)
    setup_logging(app)
    fix_sqlalchemy_uwsgi_multiprocess_bug(app)

    return app

demweb/views.py
from flask import Blueprint, render_template

from demweb.extensions import db
from demweb.models import *

bp = Blueprint('views', __name__)

@bp.route('')
def home():
    return 'hello world'

@bp.route('/session/<int:session_id>')
def session(session_id):
    session = Session.query.filter_by(id=session_id).one()
    if not session:
        return '404 Not Found', 404

    player_sessions_ = PlayerSession.query.filter_by(session_id=session_id).all()
    player_sessions = dict()
    for psess in player_sessions_:
        player_sessions[psess.player_guid] = psess
    del player_sessions_

    players_ = Player.query.filter(Player.guid.in_(player_sessions.keys()))
    players = dict()
    for player in players_:
        players[player.guid] = player
    del players_

    chats = Chat.query.filter_by(session_id=session_id).all()
    chats.sort(key=lambda x: x.tick)

    events = Event.query.filter_by(session_id=session_id).all()
    events.sort(key=lambda x: x.tick)

    return render_template('session.html',
        session=session,
        player_sessions=player_sessions,
        players=players,
        chats=chats,
        events=events
    )

@bp.route('/player/<guid>')
def player(guid):
    player = Player.query.filter_by(guid=guid).one()
    if not player:
        return '404 Not Found', 404

    player_sessions = PlayerSession.query.filter_by(player_guid=guid).all()

    return render_template('player.html',
        player=player,
        player_sessions=player_sessions
    )

demweb/templates/player.html
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>
    {{ player.guid }} - {{ player.name }}
  </title>

  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
    crossorigin="anonymous"
  />

  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/css/theme.bootstrap_4.min.css"
    integrity="sha512-2C6AmJKgt4B+bQc08/TwUeFKkq8CsBNlTaNcNgUmsDJSU1Fg+R6azDbho+ZzuxEkJnCjLZQMozSq3y97ZmgwjA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer"
  />
</head>

<body>
<main class="container">

<div class="row">
  <div class="col">
    <table class="table table-sm table-borderless">
    <tbody>
      <tr>
        <th scope="row">guid</th>
        <td>
          <a href="https://steamcommunity.com/profiles/{{ player.guid }}" target="_blank">
            {{ player.guid }}
          </a>
        </td>
      <tr>
        <th scope="row">name</th>
        <td>{{ player.name }}</td>
      <tr>
        <th scope="row">first_seen</th>
        <td>{{ player.first_seen }}</td>
      <tr>
        <th scope="row">last_seen</th>
        <td>{{ player.last_seen }}</td>
      <tr>
        <th scope="row">playtime</th>
        <td>{{ player.playtime | to_duration }}</td>
      <tr>
        <th scope="row">chats</th>
        <td>{{ player.chats }}</td>
      <tr>
        <th scope="row">deaths</th>
        <td>{{ player.deaths }}</td>
      <tr>
        <th scope="row">kills</th>
        <td>{{ player.kills }}</td>
      <tr>
        <th scope="row">voicetime</th>
        <td>{{ player.voicetime | to_duration }}</td>
    </tbody>
    </table>
  </div>

  <div class="col">
    <table class="table table-striped tablesorter" id="playerNamesTable">
    <thead>
        <tr>
        <th scope="col">Name</th>
        <th scope="col" class="sorter-duration">Time</th>
        </tr>
    </thead>
    <tbody>
    {%- for name in player.names %}
        <tr>
        <th scope="row">{{ name.name }}</th>
        <td>{{ (name.time * 0.015) | to_duration }}</td>
        </tr>
    {%- endfor %}
    </tbody>
    </table>
  </div>

  <div class="col">
    <table class="table table-striped" id="playerSpraysTable">
    <thead>
        <tr>
        <th scope="col">Spray</th>
        </tr>
    </thead>
    <tbody>
    {%- for spray in player.sprays %}
        <tr>
        <th scope="row">{{ spray.spray }}</th>
        </tr>
    {%- endfor %}
    </tbody>
    </table>
  </div>
</div>

<div class="row">
  <h3>Sessions</h3>
  <table class="table table-striped tablesorter" id="playerSessionsTable">
  <thead>
      <tr>
      <th scope="col">#</th>
      <th scope="col" class="sorter-isoDate">Time</th>
      <th scope="col" class="sorter-duration">Length</th>
      <th scope="col">Map</th>
      <th scope="col" class="sorter-duration">Playtime</th>
      <th scope="col">Chats</th>
      <th scope="col" class="sorter-duration">Voicetime</th>
      </tr>
  </thead>
  <tbody>
  {%- for session in player_sessions %}
      <tr>
      <th scope="row">
        <a href="{{ url_for('views.session', session_id=session.session.id) }}#{{ player.guid }}">
          {{ session.session.id }}
        </a>
      </th>
      <td>{{ session.session.time.isoformat(' ') }}</td>
      <td>{{ session.session.length | to_duration }}</td>
      <td>{{ session.session.mapname }}</td>
      <td>{{ session.playtime | to_duration }}</td>
      <td>{{ session.chats }}</td>
      <td>{{ session.voicetime | to_duration }}</td>
      </tr>
  {%- endfor %}
  </tbody>
  </table>
</div>
</main>

<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"
></script>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/jquery.tablesorter.min.js"
  integrity="sha512-qzgd5cYSZcosqpzpn7zF2ZId8f/8CHmFKZ8j7mU4OUXTNRd5g+ZHBPsgKEwoqxCtdQvExE5LprwwPAgoicguNg=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.3/js/parsers/parser-duration.min.js"
  integrity="sha512-X7QJLLEO6yg8gSlmgRAP7Ec2qDD+ndnFcd8yagZkkN5b/7bCMbhRQdyJ4SjENUEr+4eBzgwvaFH5yR/bLJZJQA=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

<script type="text/javascript">
$(function() {
  $("#playerNamesTable").tablesorter({
    theme: "bootstrap"
  });
  $("#playerSessionsTable").tablesorter({
    theme: "bootstrap"
  });
});
</script>

</body>
</html>

demweb/templates/session.html
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>
    {{ session.demoname }}
  </title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/main.css">
  <script src="https://kit.fontawesome.com/ef69927139.js" crossorigin="anonymous"></script>
</head>


<body>
<main>

<div class="d-flex flex-column flex-grow-1">
  <div class="btn-toolbar" role="toolbar" style="min-width: max-content;">
    <div class="btn-group me-2" role="group">
      <button type="button" class="btn-pause btn btn-outline-warning" title="Pause">
        <i class="fas fa-pause"></i>
      </button>
      <button type="button" class="btn-play btn btn-outline-success" title="Play">
        <i class="fas fa-play"></i>
      </button>
      <button type="button" class="btn-stop btn btn-outline-danger" title="Stop">
        <i class="fas fa-stop"></i>
      </button>
      <button
        type="button"
        class="btn-rewind btn btn-outline-success"
        title="Rewind"
      >
        <i class="fas fa-fast-backward"></i>
      </button>
      <button
        type="button"
        class="btn-fast-forward btn btn-outline-success"
        title="Fast forward"
      >
        <i class="fas fa-fast-forward"></i>
      </button>
    </div>

    <div class="btn-group me-2" role="group">
      <button type="button" title="Zoom in" class="btn-zoom-in btn btn-outline-dark">
        <i class="fas fa-search-plus" aria-hidden="true"></i>
      </button>
      <button type="button" title="Zoom out" class="btn-zoom-out btn btn-outline-dark">
        <i class="fas fa-search-minus" aria-hidden="true"></i>
      </button>
    </div>

    <div class="btn-group me-2">
      <div style="margin: 6px">
        <input
          type="range"
          min="0"
          max="100"
          value="50"
          class="master-gain form-range mw-50"
          id="master-gain"
        />
      </div>
    </div>

    <div class="btn-group me-2">
      <div style="margin: 6px">
        <span class="audio-pos font-monospace" aria-label="Audio position">00:00:00.0</span>
      </div>

      <div style="margin: 6px">
        <span class="audio-pos-2 font-monospace" aria-label="Audio position">00:00:00.0</span>
      </div>

      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" id="autoscroll_voice" checked>
        <label class="form-check-label" for="autoscroll_voice">Voice</label>
      </div>

      <div class="form-check form-switch">
        <label class="form-check-label" for="autoscroll_chat">Chat</label>
        <input class="form-check-input" type="checkbox" id="autoscroll_chat" checked>
      </div>
    </div>

    <div class="btn-group me-2">
      <button type="button" title="Download the selection as Wav file" class="btn btn-download btn-outline-primary">
        <i class="fas fa-download" aria-hidden="true"></i>
      </button>
    </div>
  </div>

  <div class="overflow-auto" id="playlist">
  </div>
</div>


<div class="d-flex flex-column overflow-auto" id="chat">
  <table class="table table-sm text-nowrap">
    <thead>
      <tr>
        <th scope="col">Time</th>
        <th scope="col">SteamID</th>
        <th scope="col">Name</th>
        <th scope="col">Message</th>
      </tr>
    </thead>
    <tbody>
{%- for chat in chats %}
      <tr>
        <td onclick="jumpToGameTick({{ chat.tick }})">
          {{ (chat.tick * session.tickinterval) | to_duration }}
        </td>
        <td>{{ chat.player_guid }}</td>
        <td>{{ chat.name }}</td>
        <td>{{ chat.chat }}</td>
      </tr>
{%- endfor %}
    </tbody>
  </table>
</div>

</main>


<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"
></script>

<script
  src="/static/js/waveform-playlist.var.js?v=4.0.1"
></script>

<script type="text/javascript">
var g_session = {{ session.asdict() | to_json | safe }};

var g_player_sessions = {
{%- for guid, psess in player_sessions.items() %}
"{{ guid }}": {{ psess.asdict(exclude=['player_guid', 'session_id']) | to_json | safe }},
{%- endfor %}
};

var g_chats = [
{%- for chat in chats %}
{{ chat.asdict(exclude=['id', 'session_id']) | to_json | safe }},
{%- endfor %}
];

var g_events = [
{%- for event in events %}
{{ event.asdict(exclude=['id', 'session_id']) | to_json | safe }},
{%- endfor %}
];
</script>

<script
  src="/static/js/main.js"
></script>

<script type="text/javascript">
playlist.load([
{%- for guid, psess in player_sessions.items() %}
{%- if psess.voicetime > 0 %}
{src: "/static/css-ze-parsed/{{ session.demoname }}/voice/{{ guid }}.demopus", name: "{{ guid }}", info: "{{ psess.player.name }}"},
{%- endif -%}
{% endfor %}
]).then(function() {
  onFinishedLoading();
});
</script>

</body>
</html>